BlogifyDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('',article_views.article_list,name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout',views.logout_view,name="logout")
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('',views.article_list,name="list"),
    path('create/',views.article_create,name="create"),
    path('<slug:slug>',views.article_detail,name="detail")
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] + "..."

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = {'title','body','slug','thumb'}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('articles:list')
        else:
            return redirect('accounts:signup')
    else:
        form = UserCreationForm()
        return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
        else:
            return redirect('accounts:login')
    else:
        form = AuthenticationForm()
        return render(request,'accounts/login.html',{'form':form})
    

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,"articles/article_list.html",{'articles':articles})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.author = request.user
            form_instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
        return render(request,'articles/article_create.html',{'form':form})



def article_detail(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article': article})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
        <h1>login</h1>
        <form action="{%url 'accounts:login'%}" method="post">
                {% csrf_token %}
                {{form}}
                {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{request.GET.next}}">
                {% endif %}
                <input type="submit" value="sublit">
        </form>
{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
        <h1>singup</h1>
        <form action="{%url 'accounts:signup'%}" method="post">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="sublit">
        </form>
   
{%endblock%}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>create an article</h2>
        <form action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="submit">
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}
        <h1>article list</h1>
        <div class="artile-detail">
            <div class="article">
                <img src="{{article.thumb.url}}" >
                <p>{{article.title}}</p>
                <p>{{article.body}}</p>
                <p>{{article.date}}</p>
                <p>added by : {{article.author.username}}</p>
            </div>
        </div>
{%endblock%}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
        <h1>article list</h1>
        <div class="artcles">
            {% for article in articles %}
            <div class="article">
                <h2>
                    <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a>
                </h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
            </div>
            {% endfor %}
        </div>
{%endblock%}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>

<body>
    <div class="waraper">
        <h1>
            <a href="{% url 'home' %}">logo</a>
        </h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}">create</a></li>

                {% else %}
                <li><a href="{% url 'accounts:signup' %}">sign up</a></li>
                <li><a href="{% url 'accounts:login' %}">login</a></li>
                {% endif %}
            </ul>
        </nav>
        
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'script.js'%}"></script>
</body>

</html>